# Site settings
title: John's Portfolio
author: John Goodliff
description: "John Goodliff's personal portfolio"
url: "johng.io"
github_link: "https://github.com/jerboa88.github.io"

# Change the primary color of the entire site
theme_color: "#317b71"

# File structure settings
image_path: /img

# Build settings
markdown: kramdown
permalink: pretty

# Collection definitions and settings
collections:
  projects:
    output: true
    permalink: /projects/:path/
