/*
	Skills
	------
*/

import { SkillType, type SkillsConfig } from '../../types/content/skills.ts';

export const SKILLS_CONFIG: SkillsConfig = {
	[SkillType.Languages]: [
		'Bash',
		'C/C++',
		'CSS',
		'Datalog',
		'HTML',
		'Java',
		'JavaScript/TypeScript',
		'Kotlin',
		'Liquid Template Language',
		'Lisp',
		'Lua',
		'MIPS Assembly',
		'Nix',
		'Python',
		'R',
		'SASS/SCSS',
		'SQL',
		'VBA',
	],
	[SkillType.Technologies]: [
		'CUDA',
		'Django',
		'Docker',
		'Electron',
		'FastAPI',
		'GatsbyJS',
		'Firebase',
		'Git',
		'Jekyll',
		'JSP',
		'JUnit',
		'Kubernetes',
		'Linux',
		'Next.js',
		'Node.js',
		'NumPy',
		'Oracle DB',
		'PostgreSQL',
		'Puppeteer',
		'React.js',
		'Regular Expressions',
		'Spring Framework',
		'SQLite',
		'Tailwind CSS',
		'Vue.js',
		'Webpack',
	],
	[SkillType.Tools]: [
		'Android Studio',
		'Blender',
		'GIMP',
		'GitHub',
		'Inkscape',
		'Slack',
		'Visual Studio Code',
		'Visual Studio',
	],
	[SkillType.Topics]: [
		'Agile Methodologies',
		'Code Review',
		'Communication',
		'OOP',
		'Unit Testing',
	],
} as const;
